# Generated by Django 5.1 on 2024-09-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_email_ask',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
