# Generated by Django 5.0.6 on 2024-08-03 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productscategory', verbose_name='پدر دسته بندی'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='اسلاگ محصول')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('count', models.IntegerField(verbose_name='تعداد موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='products_image', verbose_name='نصویر اصلی محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productsbrand', verbose_name='برند محصول')),
                ('category', models.ManyToManyField(to='product_module.productscategory', verbose_name='دسته بندی های محصول')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=150)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
