# Generated by Django 5.0.6 on 2024-08-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productscategory_parent_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsvisit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsproperty',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsvisit',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductsGallery',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductsProperty',
        ),
        migrations.DeleteModel(
            name='ProductsVisit',
        ),
    ]
