# Generated by Django 5.0.6 on 2024-08-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_remove_products_brand_remove_products_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsBrand',
        ),
        migrations.DeleteModel(
            name='ProductsCategory',
        ),
    ]
