# Generated by Django 5.0.6 on 2024-08-03 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='اسلاگ محصول')),
                ('title', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('count', models.IntegerField(verbose_name='تعداد موجود')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='products_image', verbose_name='نصویر اصلی محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productsbrand', verbose_name='برند محصول')),
                ('category', models.ManyToManyField(to='product_module.productscategory', verbose_name='دسته بندی های محصول')),
            ],
        ),
    ]
