# Generated by Django 5.0.6 on 2024-08-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_productsgallery_productsproperty_productsvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='product_images', verbose_name='نصویر اصلی محصول'),
        ),
    ]
