# Generated by Django 5.0.6 on 2024-08-03 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('show_author', models.BooleanField(default=True)),
                ('main_image', models.ImageField(upload_to='post_images')),
                ('caption', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='post_module.postscategory')),
            ],
        ),
    ]
