# Generated by Django 5.0.6 on 2024-08-04 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0003_postscomment_postsgallery_postvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_module.postscategory'),
        ),
        migrations.AlterField(
            model_name='postscomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post_module.postscomment'),
        ),
    ]
