# Generated by Django 5.1 on 2024-08-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0005_posts_tags_alter_posts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postscategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='poststag',
            name='is_active',
        ),
    ]
