# Generated by Django 5.1 on 2024-09-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0006_remove_postscategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='post_module.posts'),
        ),
        migrations.AlterField(
            model_name='postsgallery',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='post_module.posts'),
        ),
    ]
