# Generated by Django 5.1 on 2024-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0007_alter_postscomment_post_alter_postsgallery_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscomment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
