# Generated by Django 5.1 on 2024-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0008_alter_postscomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscomment',
            name='is_active',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
