# Generated by Django 5.1 on 2024-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0009_alter_postscomment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscomment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
