# Generated by Django 5.1 on 2024-09-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0011_alter_postvisit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='post_module.postscategory'),
        ),
        migrations.AlterField(
            model_name='poststag',
            name='url_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
