# Generated by Django 5.1 on 2024-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_module', '0012_alter_posts_category_alter_poststag_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postscategory',
            name='url_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
